### ISSUE TITLE
Haddock issue

### ISSUE THREAD

**Issue by siddharthist** [GaloisInc/llvm-verifier#21]
My own Nix build and Hydra ([fryingpan](http://fryingpan.dev.galois.com/hydra/build/111890)) are failing due to Haddock comment issues:
```
src/Verifier/LLVM/Backend.hs:130:5: error:
    parse error on input ‘-- | Interpret the term as a concrete signed integer if it can be.’
    |
130 |     -- | Interpret the term as a concrete signed integer if it can be.
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
@kquick It appears you changed these comments around in https://github.com/GaloisInc/llvm-verifier/commit/70d53915d039d6c6b56ea2afbd23765240bd896f, if you describe how they should be laid out, I'm happy to make the change.

**Comment by kquick** [comment]
Looks like I confused magit when selecting specific lines to be included in the commit.  I fixed the inadvertent reordering, and it should be OK now.

**Comment by siddharthist** [comment]
Thanks! Fixed in https://github.com/GaloisInc/llvm-verifier/commit/16600b3ddbe7cc32ed2eebae63f64b18cb78e5b0
