### ISSUE TITLE
Add support for `llvm.objectsize.*`

### ISSUE THREAD

**Issue by atomb** [GaloisInc/llvm-verifier#4]
LLVM intrinsics of the form `llvm.objectsize.*` show up increasingly often when compiling code that uses memset or memcpy with any recent version of clang, but they aren't currently supported by LSS.

**Comment by abedra** [comment]
@atomb what are you doing to demonstrate this? I dumped the ll and took a look at a few different things but haven't been able to see this anywhere.

**Comment by abedra** [comment]
Did this get added?

**Comment by atomb** [comment]
Yes. I should have referenced the commit (b957664c9c45f25f3d3f3327001c670cc757d594) closing it. The problem, it turns out, was that the intrinsic was just named incorrectly. It was implemented. I think the name may have changed since an earlier LLVM version.

**Comment by abedra** [comment]
Oh nice! Thanks!
