### ISSUE TITLE
llvm_symexec fails with "evalTermF ExtCns unimplemented "

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/llvm-verifier#9]
With this C code:

    #include <stdint.h>

    uint8_t count(uint32_t x) {
      uint8_t c = 0;
      while (x > 0) {
        x >>= 1;
        c += 1;
      }
      return c;
    }

we have something a bit odd.  Here's the saw-script:

    c <- llvm_load_module "count.bc";

    count <- llvm_extract c "count" llvm_pure;

    x <- fresh_symbolic "x" {| [32] |};
    count' <- llvm_symexec c "count" [] [("x",x,1)] [("return", 1)] true;

The llvm_extract command succeeds just fine.  The llvm_symexec line fails with the message

    evalTermF ExtCns unimplemented (x)

Somehow I imagined these two commands were pretty much equivalent, buit clearly not.

This effect happens even if I make the routine more obviously terminating, as in

    uint8_t count_2(uint32_t x) {
      uint8_t c = 0;
      for (int i = 0; i < 32; i++) {
        if (x==0) return c;
        x >>= 1;
        c += 1;
      }
      return c;
    }

This is a real problem when parameters are structs, as then llvm_extract is not an option.

**Comment by atomb** [comment]
This seems to work fine now.
